
# golangci-lint run

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - errcheck
    - gochecknoglobals
    - gocyclo
    - gocognit
    - lll
    - gomnd
    - wsl
    - scopelint
    - funlen
    - nestif

issues:
  exclude:
    - "G104: Errors unhandled." # turn off errcheck
    - "declaration of \"[a-z]\" shadows declaration at .*_test.go" # ignore shadowing a single charcter varibles in tests
    - "receiver name [a-z]0 should be consistent with previous receiver name [a-z]" # when we want to operate on a copy
    - "error strings should not be capitalized or end with punctuation or a newline" # doesn't matter
    - "lines are duplicate of `crc.crc.go:" # ignore duplications in crc.go
    - "package should be `crc_test` instead of `crc`" # ignore white listed internal testing
    - "Top level comment should end in a period" 

output:
  format: line-number